apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l55kocd2i-python
  janus-idp.io/tekton: l55kocd2i-python
  backstage.io/kubernetes-id: l55kocd2i-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l55kocd2i-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
